### ISSUE TITLE
Support for batch processing on response with status 202?

### ISSUE THREAD

**Issue by mqchau** [graphiti-api/spraypaint.js#23]
Hi, I'm looking to follow this JSON:API *recommendation* for batch processing:

https://jsonapi.org/recommendations/#asynchronous-processing

My use case is that I have a delete that is super slow (many minutes). I would like to put that into the background job, then return the job details in the 202 response like that document says.

I look into our source code and see this
https://github.com/graphiti-api/spraypaint.js/blob/de34db399b49783398c26ac0a052c3c74289ec9d/src/model.ts#L907
That means it will ignore the response with status 202.

I realize that there is a difficulty with implementing this feature: the model returned by the response is usually completely different from the model that is deleted. I'm not sure how to look up the appropriate model based on the type in the response.

**Comment by mqchau** [comment]
Upon closer look. I find that you guys already did a registry for all available type: 

https://github.com/graphiti-api/spraypaint.js/blob/de34db399b49783398c26ac0a052c3c74289ec9d/test/unit/model.test.ts#L279

So I can just based on that and try to use it on the response.

My question is: are you guys welcome to my attempt to implement this JSON:API recommendation?

**Comment by richmolj** [comment]
Hey @mqchau!

I would love to get this in myself - not just allowing a 202, but polling against the job automatically and performing an action when it's done. Is this something you'd like to submit a PR for?

**Comment by mqchau** [comment]
Hi Lee,

Thank you for being open-minded.

I wouldn't assume polling for job status. Different apps implement
different ways to display job progress. Even from within our apps we have 2
ways:
- For simple job: it returns a string that is the topic on Pusher.com to
subscribe to for job status. The subscription and reaction is done via a
dedicated React component. We moved away from polling recently.
- For more complicated job that includes 20 smaller jobs: it returns a URL
to a dedicated page with 20 small progress bars, each of them uses the
above method.

I think the responsibility of spraypaint.js stops at deserializing the
response payload and return the object in the payload. Then the application
code can do whatever it wants.

**Comment by richmolj** [comment]
> I think the responsibility of spraypaint.js stops at deserializing the
response payload and return the object in the payload. Then the application
code can do whatever it wants.

I agree that this is the *minimum* responsibility, and devs should be able to do this and nothing else. But there's an *optional/additional* responsibility of calling a hook (like `onDeferredCreate`). That way we can implement a default hook (or opt-in to this behavior) of polling against a response URL.

**Comment by mqchau** [comment]
Can I just implement the minimum responsibility approach for now?

**Comment by richmolj** [comment]
Yes, I think that's fine

**Comment by richmolj** [comment]
And much appreciated ❤️ 🙂
