### ISSUE TITLE
422 Validation Errors

### ISSUE THREAD

**Issue by askeyt** [graphiti-api/spraypaint.js#28]
Hi,

We are using Spraypaint with another JSONAPI compliant backend. The backend returns validation errors as 400's, while Spraypaint explicitly looks for 422's. The result is an "invalid json" exception being thrown, when in fact it's not. This also means I am cut off short when trying to get access to the errors payload.

Can you make the 422 validation status code configurable? or at least refactor the code to spit out the payload so I can handle it myself?

Thanks

**Comment by richmolj** [comment]
Hey @askeyt - since we require a Graphiti payload to build full, robust errors I think we'd have to just allow access to the response payload. As a Graphiti user this isn't a priority for me but I can point you in the right direction if you'd like to PR!

* [Hit here to grab the 400 response](https://github.com/graphiti-api/spraypaint.js/blob/06c8a4a1b85f235e0301c51996edfa80d639c79f/src/model.ts#L1011-L1012)
* [Add 400 to here to get past the lower-level request processing](https://github.com/graphiti-api/spraypaint.js/blob/06c8a4a1b85f235e0301c51996edfa80d639c79f/src/request.ts#L147-L148)

That said, the tricky part here is that it would need to be a configuration option, since this should be handled differently for users with Graphiti backends. It might be better to look at the response JSON from the thrown error:

```ts
// or promise.catch with promises

try {
  await model.save()
} catch(e) {
  e.response // response from server
}
```

Does that work?

**Comment by nattyg93** [comment]
@richmolj

Ideally this would be supported via a configuration option, as it was stated in [this comment](https://github.com/graphiti-api/spraypaint.js/issues/6#issuecomment-466707164) that this package will be maintaining compatibility with the JSON:API spec. The JSON:API spec does not outline a requirement for validation errors to be 422s, this behaviour is backwards incompatible.

That being said, in your example above, is there a way to get the JSON from the response in the catch?

i.e.
```typescript
try {
  await model.save()
} catch(e) {
  e.response.json()  //  throws "TypeError: Body has already been consumed." due to the call of json() here: https://github.com/graphiti-api/spraypaint.js/blob/06c8a4a1b85f235e0301c51996edfa80d639c79f/src/request.ts#L128
}
```

**Comment by richmolj** [comment]
> The JSON:API spec does not outline a requirement for validation errors to be 422s, this behaviour is backwards incompatible.

I'm not sure this is true. The JSON:API spec is vague here, and we are necessarily specific to get this functionality. While this is backwards-incompatible for *your* API (which also makes a necessarily specific choice), I don't think it's backwards-incompatible with the spec itself.

We require a specific payload for validation errors (given if you use a Graphiti backend), so the only thing we can do here without that payload is reject the promise.

That said, you should be able to get the body. I think we just need to change [this line](https://github.com/graphiti-api/spraypaint.js/blob/master/src/request.ts#L128) to `response.clone().json()` and add a test if you'd like to submit a PR!

**Comment by askeyt** [comment]
@richmolj - this change should work yes. However it would be great to be able to use the spraypaint error handling as documented (hence a config option for 422).

Alternatively (and I haven't looked into the specifics of the following suggestion just yet... so excuse me if I miss something obvious...), assuming backends are following the JSONAPI spec for error documents (https://jsonapi.org/format/#errors), the 422 check [here](https://github.com/graphiti-api/spraypaint.js/blob/06c8a4a1b85f235e0301c51996edfa80d639c79f/src/model.ts#L1011-L1012) could be changed to a 4xx, and the ValidationErrorBuilder modified to parse a valid error doc - if the response is not a valid error doc, throw invalid json.

thoughts?

**Comment by sherbrow** [comment]
Hello,

We've encountered the same need, to access errors given by our non-graphiti API, and for now we are going to work around it with the middleware `afterFilters` ([doc](https://www.graphiti.dev/js/middleware)).

Middleware would be defined as :
```js
const middleware = new MiddlewareStack();

middleware.afterFilters.push((response, json) => {
    response.errors = json.errors || [];
});

ApplicationRecord.middlewareStack = middleware;
```

And access to the errors would be done via the response property of the error :
```js
model.save().catch((error) => {
    jsonApiErrors = error.response.errors;
});
```

**Comment by kevinjbayer** [comment]
Thanks, @sherbrow. I'm trying out a Graphiti-Rails backend with a Nuxt frontend using Spraypaint and was hitting this same error. Your workaround was successful for me to reach the errors as well. 🙌

**Comment by richmolj** [comment]
Apologies for the delay here, and thanks to @sherbrow for a great path forward. I'd also be happy to merge a PR that fixes in Spaypaint directly.

@askeyt I'd be happy to support non-graphiti backends, but unfortunately vanilla JSON:API does not give us enough information to do what we need -  nested validations is one example. Another is type errors versus validation errors (400 vs 422). So we'd be trying to hit an ever-moving target of inconsistent backends. I'm happy to work with a PR that adds the support you need, but for me personally it's a bit too much of a black hole I'd like to avoid.

**Comment by askeyt** [comment]
@richmolj sorry for the radio silence also. we have just added in @sherbrow 's work around and that will suffice for now. Totally understand your hesitation trying to cater for all the possibilities. 

And as you said, the response.clone().json() _should_ remove the need for the workaround, so if that sneaks into one of your future releases I'd be more than happy ;)

Tim

**Comment by Petercopter** [comment]
Hey guys, I feel like I'm going crazy. When I catch the error, all I get is the error, I don't have a `response` key in there. I've read the tests, I see that the `clone()` is already in (probably unrelated), I've checked Slack, I just don't understand what I'm doing wrong.

```
model.save().catch(e => console.log(e))
```
Results in
```
POST http://localhost:3000/frontend/v1/objective-types 422 (Unprocessable Entity)
TypeError: Cannot read property 'relationship' of undefined
    at index.js:8102
    at Array.forEach (<anonymous>)
    at ValidationErrorBuilder.push../node_modules/spraypaint/lib-esm/util/validation-error-builder.js.ValidationErrorBuilder.apply (index.js:8100)
    at Function.push../node_modules/spraypaint/lib-esm/util/validation-error-builder.js.ValidationErrorBuilder.apply (index.js:8092)
    at Subclass.<anonymous> (index.js:6634)
    at step (index.js:8522)
    at Object.next (index.js:8503)
    at index.js:8496
    at new Promise (<anonymous>)
    at Module.__awaiter (index.js:8492)
```

**Comment by nobitagit** [comment]
@Petercopter did you try logging the response directly, as in:

```js
model.save().catch(e => console.log(e.response))
```

Which is basically the same as [the example above with async/await](https://github.com/graphiti-api/spraypaint.js/issues/28#issuecomment-491269075).

**Comment by Petercopter** [comment]
@nobitagit Thanks for checking this out, the `response` key is undefined. I've got the middleware setup, it's definitely firing during the request, I can see the full response inside the `afterFilters` method. Here's what I'm seeing when I debug the response inside the catch block:
![image](https://user-images.githubusercontent.com/1493974/65982411-28779700-e430-11e9-9310-9738c184c2bf.png)

As you can see, there's no `response` key. This is happening inside a Vue.js/Nuxt application.

**Comment by Petercopter** [comment]
OK I think I'm finally onto something. The reason it's not working as expected is because I'm getting a `TypeError`, not a `ResponseError`. If I manually throw a `ResponseError`, then things work as expected. I adjusted the middleware like this:

```
middleware.afterFilters.push((response, json) => {
  if (json.errors) {
    response.errors = json.errors || []
    throw ResponseError
  }
})
```
