### ISSUE TITLE
created_at not coming through to Spraypaint model

### ISSUE THREAD

**Issue by markokoen** [graphiti-api/spraypaint.js#72]
Hi There,

'created_at' appears in the api and I can see the raw json but comes through as 'undefined' in the spraypaint model in my angular frontend. Note: we are using the Mongoid adapter which I will include below as well.

How can I debug the spraypaint code to see why the attributes are not coming through to the spraypaint model?

Please advise

```
# order.rb Model:

class Order
  include Mongoid::Document
  include Mongoid::Timestamps

  field :created_at, type: DateTime

end


# order_resource.rb Resources:

class OrderResource < ApplicationResource
  self.adapter = Graphiti::Adapters::Mongoid

  attribute :created_at, :datetime

end

// Spraypaint angular frontend model:
// OrderResource.ts

@Model()
export class OrderResource extends ApplicationRecord {
  static jsonapiType = "orders"

@Attr() created_at: string

}


# mongoid.rb Adapter

module Graphiti
  module Adapters
    class Mongoid < ::Graphiti::Adapters::Abstract

      def base_scope(model)
        model.all
      end

      def paginate(scope, current_page, per_page)
        scope.page(current_page).per(per_page)
      end

      def resolve(scope)
        scope.to_a
      end

      def order(scope, attribute, direction)
        scope.order(attribute => direction)
      end
    end
  end
end


```

**Comment by markokoen** [comment]
@richmolj

**Comment by elDub** [comment]
By default I believe client-side casing is set to camelCase, in which I think:
```@Attr() created_at: string```
should be
```@Attr() createdAt: string```

I have not tried this out, but that is just my observation.

**Comment by markokoen** [comment]
@elDub Next level! Thanks, that worked for me. Much appreciated!
